version: '3.7'

services:

    web:
        build: .
        ports:
        - "4000:4000"
        links:
        - mongodb

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: user
        ports:
            - 27017:27017
        volumes:
            - ./mongo_db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./Users/adrianlee/Desktop/mongoDB_data:/data/db mongo