apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: web
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: leexha/node_demo:23
        env:
        - name: MONGODB_URL
          value: "mongodb://mongo.default.svc.cluster.local:27017/user"
        name: web
        ports:
        - containerPort: 4000
          name: web