apiVersion: v1
kind: Service
metadata:
  name: sps-app
  labels:
    name: sps-app
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    name: sps-app

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sps
spec:
  rules:
  - host: sps.corp.local
    http:
      paths:
      - backend:
          serviceName: sps-app
          servicePort: 4000