apiVersion: v1
kind: Service
metadata:
  name: sps-app
  labels:
    name: sps-app
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    name: sps

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sps
spec:
  rules:
  - host: sps.pks-cl01-apps.acepod.com
    http:
      paths:
      - backend:
          serviceName: sps
          servicePort: 4000